trigger:
- master

jobs:
- job: 'PrivateWindows'
  pool:
    name: 'Self-hosted pool'
    demands:
    - Agent.Name -equals test-extract-tasks
  steps:
  # - task: Bash@3
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       # Write your commands here
        
  #       echo 'Hello world'
  # - task: Bash@3
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       # Write your commands here
        
  #       echo 'Hello world'
  # - task: Bash@3
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       # Write your commands here
        
  #       echo 'Hello world'

  - template: ci/template.yml

# - job: 'HostedWindows'
#   pool:
#     vmImage: windows-latest
#   #condition: and(succeeded())
#   steps:
#   - template: ci/template.yml

# - job: 'HostedMacOS'
#   pool:
#     vmImage: macOS-latest
#   #condition: and(succeeded())
#   steps:
#   - template: ci/template.yml

# - job: 'HostedUbuntu'
#   pool:
#     vmImage: ubuntu-latest
#   #condition: and(succeeded())
#   steps:
#   - template: ci/template.yml