# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Self-hosted pool'
  demands:
  - Agent.Name -equals Agent 2

steps:
- task: PublishBuildArtifacts@1
  displayName: 'Publish test build artifact'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'
    ArtifactName: 'test'
    publishLocation: 'Container'


- task: DownloadBuildArtifacts@0
  displayName: 'Download all artifact items'
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'test'
    downloadPath: '$(System.ArtifactsDirectory)/fullArtifact/'

- task: DownloadBuildArtifacts@0
  displayName: 'Download only *.c filles from nested folder'
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'test'
    itemPattern: 'test/Example/Myartifact/Subfolder/Ab/*.c'
    downloadPath: '$(System.ArtifactsDirectory)/onlyCFiles'

- task: DownloadBuildArtifacts@0
  displayName: 'Download only *.yaml filles from nested folder'
  inputs:
    buildType: 'current'
    downloadType: 'specific'
    itemPattern: 'test/*.yml'
    downloadPath: '$(System.ArtifactsDirectory)/onlyYamlFile'