trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  # name: 'Self-hosted pool'
  # demands:
  # - Agent.Name -equals Agent 2

jobs:
- job: WindowsContainer
  container: mcr.microsoft.com/windows/servercore:latest
  steps:
  - template: ./ci/template.yml

  # - template: ci/template.yml

# - job: 'HostedWindows'
#   pool:
#     vmImage: windows-latest
#   #condition: and(succeeded())
#   steps:
#   - template: ci/template.yml

# - job: 'HostedMacOS'
#   pool:
#     vmImage: macOS-latest
#   #condition: and(succeeded())
#   steps:
#   - template: ci/template.yml

# - job: 'HostedUbuntu'
#   pool:
#     vmImage: ubuntu-latest
#   #condition: and(succeeded())
#   steps:
#   - template: ci/template.yml