trigger:
- master

jobs:
- job: 'HostedWindows'
  pool:
    name: 'Self-hosted pool'
    demands:
    - Agent.Name -equals Agent 2
  steps:
  - template: ci/template.yml


# jobs:
# - job: 'HostedWindows'
#   pool:
#     vmImage: windows-latest
#   #condition: and(succeeded())
#   steps:
#   - template: ci/template.yml

# - job: 'HostedMacOS'
#   pool:
#     vmImage: macOS-latest
#   #condition: and(succeeded())
#   steps:
#   - template: ci/template.yml

# - job: 'HostedUbuntu'
#   pool:
#     vmImage: ubuntu-latest
#   #condition: and(succeeded())
#   steps:
#   - template: ci/template.yml