# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Self-hosted pool'
  demands:
  - Agent.Name -equals "Agent 2"

steps:
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'
    ArtifactName: 'test'
    publishLocation: 'Container'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: '69af9ebb-49cb-4073-8269-d85b37b38e74'
    pipeline: '21'
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'test'
    downloadPath: '$(System.ArtifactsDirectory)'

# - task: PublishPipelineArtifact@1
#   inputs:
#     targetPath: '$(Build.SourcesDirectory)/Example/Myartifact/'
#     artifact: 'Myartifact - PipelineArtifact'
#     publishLocation: 'pipeline'