# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest
  # name: 'Self-hosted pool'
  # demands:
  # - Agent.Name -equals Agent 2

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mkdir TestCases
      cd TestCases
      
      mkdir SourceFiles
      touch SourceFiles/sample_1.c
      touch SourceFiles/sample_2.c
      touch SourceFiles/sample_3.cpp
      touch SourceFiles/sample_4.cpp

      mkdir HeaderFiles
      touch HeaderFiles/sample_1.h
      touch HeaderFiles/sample_2.h
      touch HeaderFiles/sample_3.hpp
      touch HeaderFiles/sample_4.hpp

      pwd
      ls -la

- task: PublishBuildArtifacts@1
  displayName: 'Publish source files'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/TestCases/SourceFiles'
    ArtifactName: 'Artifact_SourceFiles'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Publish header files'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/TestCases/HeaderFiles'
    ArtifactName: 'Artifact_HeaderFiles'
    publishLocation: 'Container'

- task: DownloadBuildArtifacts@0
  displayName: 'Download only source files'
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'Artifact_SourceFiles'
    downloadPath: '$(System.ArtifactsDirectory)/TestCases/1_OnlySourceFiles/'

- task: DownloadBuildArtifacts@0
  displayName: 'Download only header files'
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'Artifact_SourceFiles'
    downloadPath: '$(System.ArtifactsDirectory)/TestCases/2_OnlyHeaderFiles/'

- task: DownloadBuildArtifacts@0
  displayName: 'Download only *.c files'
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'Artifact_SourceFiles'
    itemPattern: 'Artifact_SourceFiles/*.c'
    downloadPath: '$(System.ArtifactsDirectory)/TestCases/3_OnlyCFiles/'

- task: DownloadBuildArtifacts@0
  displayName: 'Download only *.hpp files'
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'Artifact_HeaderFiles'
    itemPattern: 'Artifact_HeaderFiles/*.hpp'
    downloadPath: '$(System.ArtifactsDirectory)/TestCases/4_OnlyHPPFiles/'

- task: DownloadBuildArtifacts@0
  displayName: 'Download *.cpp and *.hpp files'
  inputs:
    buildType: 'current'
    downloadType: 'specific'
    itemPattern: |
      Artifact_SourceFiles/*.cpp
      Artifact_HeaderFiles/*.hpp
    downloadPath: '$(System.ArtifactsDirectory)/TestCases/5_CppFiles/'

- task: DownloadBuildArtifacts@0
  displayName: 'Download *.c and *.h files'
  inputs:
    buildType: 'current'
    downloadType: 'specific'
    itemPattern: |
      Artifact_SourceFiles/*.c
      Artifact_HeaderFiles/*.h
    downloadPath: '$(System.ArtifactsDirectory)/TestCases/6_CFiles/'

- task: DownloadBuildArtifacts@0
  displayName: 'Download *.c and *.h files'
  inputs:
    buildType: 'current'
    downloadType: 'specific'
    itemPattern: |
      Artifact_SourceFiles/*.c
      Artifact_HeaderFiles/*.h
    downloadPath: '$(System.ArtifactsDirectory)/TestCases/7_AllFiles/'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd $(System.ArtifactsDirectory)/
      ls -R